import{db}from'./firebase-config.js';import{collection,getDocs}from'https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js';
const params=new URLSearchParams(location.search),exam=params.get('exam'),subject=params.get('subject');let qs=[],ready=false,lang=localStorage.getItem('trueReviseLang')||'en',lastIndex=-1,renderToken=0,translationCache=new Map();const $=id=>document.getElementById(id);
function hasTe(q){return !!(q?.hasTelugu||q?.questionTe||q?.explanationTe||Object.values(q?.optionsTe||{}).some(Boolean));}
function optionText(q,l){return q?.optionsTe?.[l]||q?.options?.[l]||q?.['option'+l]||'';}
function renderOption(l,text,q){const el=$('option'+l);if(!el)return;el.innerHTML='';const wrap=document.createElement('div');wrap.className='option-content';const span=document.createElement('span');span.className='option-text';span.textContent=`${l}. ${text||''}`;wrap.appendChild(span);const src=(q.optionImageUrls||q.optionImages||{})[l]||'';if(src){const img=document.createElement('img');img.className='option-image';img.src=src;img.alt=`Option ${l} diagram`;img.loading='lazy';wrap.appendChild(img)}el.appendChild(wrap)}
function currentIndex(){const text=$('questionNo')?.textContent||'';const m=text.match(/Question\s+(\d+)/i);return m?Number(m[1])-1:-1}
function updateLanguageMenu(q){const teBtn=document.querySelector('#langMenu button[data-lang="te"]');const enBtn=document.querySelector('#langMenu button[data-lang="en"]');const available=hasTe(q);if(teBtn){teBtn.style.display='block';teBtn.textContent=available?'🇮🇳 తెలుగు':'🇮🇳 తెలుగు (Google Translate)';}if(enBtn)enBtn.textContent='🇬🇧 English';if(!available&&lang==='te'){} }
async function googleTranslate(text){const source=String(text||'').trim();if(!source)return'';const key='en-te:'+source;if(translationCache.has(key))return translationCache.get(key);const urls=[`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=te&dt=t&ie=UTF-8&oe=UTF-8&q=${encodeURIComponent(source)}`,`https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=te&dt=t&ie=UTF-8&oe=UTF-8&q=${encodeURIComponent(source)}`];for(const url of urls){try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);const r=await fetch(url,{method:'GET',headers:{Accept:'application/json,text/plain,*/*'},signal:controller.signal});clearTimeout(timeout);if(!r.ok)continue;const d=await r.json();const t=(Array.isArray(d?.[0])?d[0]:[]).map(x=>x?.[0]||'').join('').trim();if(t){translationCache.set(key,t);return t}}catch(e){console.warn('Google Telugu translation unavailable:',e.message)}}return''}
async function translateFields(q){const items=[q?.question||'',q?.optionA||q?.options?.A||'',q?.optionB||q?.options?.B||'',q?.optionC||q?.options?.C||'',q?.optionD||q?.options?.D||'',q?.explanation||''];const out=await Promise.all(items.map(googleTranslate));return{question:out[0]||items[0],options:{A:out[1]||items[1],B:out[2]||items[2],C:out[3]||items[3],D:out[4]||items[4]},explanation:out[5]||items[5]}}
async function renderStored(){if(!ready)return;const i=currentIndex();if(i<0||!qs[i])return;const q=qs[i],available=hasTe(q),token=++renderToken;updateLanguageMenu(q);if(i===lastIndex&&lang===window.__storedRenderedLang)return;lastIndex=i;if(lang==='en'){$('question').textContent=`${i+1}. ${q.question||'Question not available'}`;['A','B','C','D'].forEach(l=>renderOption(l,q.options?.[l]||q['option'+l]||'',q));$('translateStatus').textContent='English • Original question text';window.__storedRenderedLang=lang;return}$('translateStatus').textContent=available?'🇮🇳 Loading saved Telugu…':'🇮🇳 Translating with Google…';let translated;if(available){translated={question:q.questionTe||q.question||'',options:{A:optionText(q,'A'),B:optionText(q,'B'),C:optionText(q,'C'),D:optionText(q,'D')},explanation:q.explanationTe||q.explanation||''}}else{translated=await translateFields(q)}if(token!==renderToken)return;$('question').textContent=`${i+1}. ${translated.question||q.question||''}`;['A','B','C','D'].forEach(l=>renderOption(l,translated.options[l]||q.options?.[l]||q['option'+l]||'',q));const exp=translated.explanation||'';const existing=document.querySelector('#translatedExplanation');if(existing)existing.remove();if(exp){const box=document.createElement('div');box.id='translatedExplanation';box.className='translated-explanation';box.textContent=exp;box.style.cssText='margin-top:14px;padding:12px 14px;border:1px solid #303b4b;border-radius:10px;background:#101722;color:#dce5f2;line-height:1.6;font-size:13px';$('testArea')?.appendChild(box)}$('translateStatus').textContent=available?'🇮🇳 Telugu • Saved Telugu version':'🇮🇳 Telugu • Google Translate';window.__storedRenderedLang=lang}
async function load(){try{const snap=await getDocs(collection(db,'questions'));qs=snap.docs.map(d=>({id:d.id,...d.data()})).filter(q=>String(q.exam||'').trim()===String(exam||'').trim()&&String(q.subject||'').trim()===String(subject||'').trim()).sort((a,b)=>Number(a.questionNumber||0)-Number(b.questionNumber||0));ready=true;renderStored();}catch(e){console.warn('Stored Telugu loader unavailable:',e.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('#langMenu button[data-lang]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const requested=b.dataset.lang;if(requested==='te'){lang='te'}else{lang='en'}localStorage.setItem('trueReviseLang',lang);lastIndex=-1;window.__storedRenderedLang='';renderStored();const menu=$('langMenu');if(menu)menu.classList.remove('show');},true);
new MutationObserver(()=>{const i=currentIndex();if(i!==lastIndex||lang==='te'){renderStored();}else{const q=qs[i];if(q)updateLanguageMenu(q);}}).observe($('questionNo')||document.body,{childList:true,subtree:true,characterData:true});
load();