import{db}from'./firebase-config.js';import{collection,getDocs}from'https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js';
const params=new URLSearchParams(location.search),exam=params.get('exam'),subject=params.get('subject');let qs=[],ready=false,lang=localStorage.getItem('trueReviseLang')||'en',lastIndex=-1;const $=id=>document.getElementById(id);
function hasTe(q){return !!(q?.hasTelugu||q?.questionTe||q?.explanationTe||Object.values(q?.optionsTe||{}).some(Boolean));}
function optionText(q,l){return q?.optionsTe?.[l]||q?.options?.[l]||q?.['option'+l]||'';}
function renderOption(l,text,q){const el=$('option'+l);if(!el)return;el.innerHTML='';const wrap=document.createElement('div');wrap.className='option-content';const span=document.createElement('span');span.className='option-text';span.textContent=`${l}. ${text||''}`;wrap.appendChild(span);const src=(q.optionImageUrls||q.optionImages||{})[l]||'';if(src){const img=document.createElement('img');img.className='option-image';img.src=src;img.alt=`Option ${l} diagram`;img.loading='lazy';wrap.appendChild(img)}el.appendChild(wrap)}
function currentIndex(){const text=$('questionNo')?.textContent||'';const m=text.match(/Question\s+(\d+)/i);return m?Number(m[1])-1:-1}
function updateLanguageMenu(q){const teBtn=document.querySelector('#langMenu button[data-lang="te"]');const enBtn=document.querySelector('#langMenu button[data-lang="en"]');const available=hasTe(q);if(teBtn){teBtn.style.display=available?'block':'none';teBtn.textContent='🇮🇳 తెలుగు';}if(enBtn)enBtn.textContent='🇬🇧 English';if(!available&&lang==='te'){lang='en';localStorage.setItem('trueReviseLang','en');}}
function renderStored(){if(!ready)return;const i=currentIndex();if(i<0||!qs[i])return;const q=qs[i],available=hasTe(q);updateLanguageMenu(q);if(i===lastIndex&&lang===window.__storedRenderedLang)return;lastIndex=i;if(lang==='te'&&available){$('question').textContent=`${i+1}. ${q.questionTe||q.question||''}`;['A','B','C','D'].forEach(l=>renderOption(l,optionText(q,l),q));$('translateStatus').textContent='🇮🇳 తెలుగు • Saved Telugu version';}else{$('question').textContent=`${i+1}. ${q.question||'Question not available'}`;['A','B','C','D'].forEach(l=>renderOption(l,q.options?.[l]||q['option'+l]||'',q));$('translateStatus').textContent=available?'English • Original question text':'English • Telugu not available for this question';}window.__storedRenderedLang=lang;}
async function load(){try{const snap=await getDocs(collection(db,'questions'));qs=snap.docs.map(d=>({id:d.id,...d.data()})).filter(q=>String(q.exam||'').trim()===String(exam||'').trim()&&String(q.subject||'').trim()===String(subject||'').trim()).sort((a,b)=>Number(a.questionNumber||0)-Number(b.questionNumber||0));ready=true;renderStored();}catch(e){console.warn('Stored Telugu loader unavailable:',e.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('#langMenu button[data-lang]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const requested=b.dataset.lang;if(requested==='te'&&!hasTe(qs[currentIndex()]))return;lang=requested;localStorage.setItem('trueReviseLang',lang);lastIndex=-1;renderStored();const menu=$('langMenu');if(menu)menu.classList.remove('show');},true);
new MutationObserver(()=>{const i=currentIndex();if(i!==lastIndex){renderStored();}else{const q=qs[i];if(q)updateLanguageMenu(q);}}).observe($('questionNo')||document.body,{childList:true,subtree:true,characterData:true});
load();
