import { auth, db } from './firebase-config.js';
import { collection, getDocs, writeBatch, doc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js';

const SUPER_ADMINS=['commercewithkiransingh@gmail.com','kiransingh.smile@gmail.com'];
const $=id=>document.getElementById(id);
let parsed=[];
let authed=false;
function isSuperAdmin(u){return !!(u?.email&&SUPER_ADMINS.includes(u.email.toLowerCase()));}
async function initAdmin(){try{await auth.authStateReady();const u=auth.currentUser;if(!isSuperAdmin(u)){location.replace('admin.html');return;}authed=true;await loadChoices();}catch(e){console.error(e);location.replace('admin.html');}}
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function normalize(text){return String(text||'').replace(/\r\n?/g,'\n').replace(/[\u00a0\u2007\u202f]/g,' ').replace(/[“”]/g,'\"').replace(/[‘’]/g,"'");}
function slug(v){return String(v).trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100);}
function examDocId(name){return 'exam-'+slug(name);}function subjectDocId(name){return 'subject-'+slug(name);}
async function loadChoices(){try{const examSnap=await getDocs(collection(db,'exams'));const exams=examSnap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.name||x.title);const subjectSet=new Set();examSnap.docs.forEach(d=>{const s=d.data().subject;if(s)subjectSet.add(String(s).trim());});try{const subSnap=await getDocs(collection(db,'subjects'));subSnap.docs.forEach(d=>{const s=d.data().name||d.id;if(s)subjectSet.add(String(s).trim());});}catch(e){}fillSelect('exam',exams.map(x=>x.name||x.title).filter(Boolean).sort((a,b)=>a.localeCompare(b)),'Telangana SET');fillSelect('subject',[...subjectSet].filter(Boolean).sort((a,b)=>a.localeCompare(b)),'Commerce Paper 2');}catch(e){setStatus('Could not load exam/subject choices: '+e.message,true);}}
function fillSelect(id,items,preferred){const s=$(id);s.innerHTML='';if(!items.length)items=[preferred];[...new Set(items)].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o);});if(preferred&&items.includes(preferred))s.value=preferred;}
function showNew(type){$(type==='exam'?'newExamBox':'newSubjectBox').style.display='block';$(type==='exam'?'newExam':'newSubject').focus();}
async function saveChoice(type){const input=$(type==='exam'?'newExam':'newSubject'),name=input.value.trim();if(!name){setStatus(`Enter a ${type} name first.`,true);return;}try{if(type==='exam')await setDoc(doc(db,'exams',examDocId(name)),{name,title:name,status:'draft',enabled:true,createdBy:auth.currentUser?.email||'',updatedAt:serverTimestamp()},{merge:true});else await setDoc(doc(db,'subjects',subjectDocId(name)),{name,createdBy:auth.currentUser?.email||'',updatedAt:serverTimestamp()},{merge:true});const select=$(type==='exam'?'exam':'subject');if(![...select.options].some(o=>o.value===name)){const o=document.createElement('option');o.value=name;o.textContent=name;select.appendChild(o);}select.value=name;input.value='';$(type==='exam'?'newExamBox':'newSubjectBox').style.display='none';setStatus(`✓ ${type[0].toUpperCase()+type.slice(1)} added successfully.`);if(type==='exam')$('previousExam').value=name;}catch(e){setStatus(`Could not save ${type}: ${e.message}`,true);}}
$('addExam').onclick=()=>showNew('exam');$('addSubject').onclick=()=>showNew('subject');$('saveExam').onclick=()=>saveChoice('exam');$('saveSubject').onclick=()=>saveChoice('subject');$('toggleIndividual').onclick=()=>{const box=$('individualForm'),show=box.style.display!=='block';box.style.display=show?'block':'none';$('toggleIndividual').textContent=show?'Hide Individual Question Form':'Show Individual Question Form';};
function setStatus(text,error=false){$('status').className='status'+(error?' error':'');$('status').textContent=text;}function setIndividualStatus(text,error=false){$('individualStatus').className='status'+(error?' error':'');$('individualStatus').textContent=text;}
async function nextQuestionNumber(exam,subject){const snap=await getDocs(collection(db,'questions'));let max=0;snap.docs.forEach(d=>{const q=d.data();if(String(q.exam||'').trim()===exam&&String(q.subject||'').trim()===subject){const n=Number(q.questionNumber);if(Number.isFinite(n)&&n>max)max=n;}});return max+1;}
function parseLabeled(block,label){const re=new RegExp('(?:^|\\n)\\s*'+label+'\\s*:\\s*([\\s\\S]*?)(?=\\n\\s*(?:English|Telugu|Explanation|Telugu Explanation|Tags?)\\s*:|$)','i');const m=block.match(re);return m?m[1].trim():'';}
function parseOptions(block,prefix=''){const out={A:'',B:'',C:'',D:''};const re=prefix==='te'?/(?:^|\n)\s*\(([ABCD])(?:-Telugu)?\)\s*/gi:/(?:^|\n)\s*\(([ABCD])\)\s*/gi;const os=[...block.matchAll(re)];if(os.length>=4){for(let j=0;j<os.length;j++){const k=os[j][1].toUpperCase(),from=os[j].index+os[j][0].length,to=j+1<os.length?os[j+1].index:block.length;if(!out[k])out[k]=block.slice(from,to).trim();}}return out;}
function parseQuestions(text){const normalized=normalize(text),re=/^\s*(?:Q(?:uestion)?\s*)0*(\d{1,3})\s*[.):-]\s*/gim,starts=[...normalized.matchAll(re)],out=[];for(let i=0;i<starts.length;i++){const start=starts[i].index,end=i+1<starts.length?starts[i+1].index:normalized.length,num=Number(starts[i][1]);let block=normalized.slice(start,end).trim().replace(/^\s*(?:Q(?:uestion)?\s*)0*\d{1,3}\s*[.):-]\s*/i,'').trim();const tm=block.match(/(?:^|\n)\s*Tags?\s*:\s*([^\n]*)/i),questionTags=tm?tm[1].split(',').map(x=>x.trim().toLowerCase()).filter(Boolean):[];if(tm)block=(block.slice(0,tm.index)+block.slice(tm.index+tm[0].length)).trim();const em=block.match(/(?:^|\n)\s*Explanation\s*:\s*([\s\S]*)$/i);let explanation=em?em[1].trim():'';if(em)block=block.slice(0,em.index).trim();const am=block.match(/(?:^|\n)\s*Answer\s*:\s*\(?\s*(A|B|C|D|ALL|MULTIPLE|DELETED)\s*\)?/i),correctAnswer=am?am[1].toUpperCase():'';if(am)block=block.slice(0,am.index).trim();let teQuestion=parseLabeled(block,'Telugu Question');let teExplanation='';const tem=block.match(/(?:^|\n)\s*Telugu Explanation\s*:\s*([\s\S]*)$/i);if(tem){teExplanation=tem[1].trim();block=block.slice(0,tem.index).trim();}let enQuestion=block;const emq=block.match(/(?:^|\n)\s*English Question\s*:\s*([\s\S]*?)(?=\n\s*Telugu Question\s*:|$)/i);if(emq){enQuestion=emq[1].trim();block=block.slice(0,emq.index).trim();}const enOptions=parseOptions(block);const teBlock=teQuestion;const teOptions=parseOptions(teBlock,'te');if(teQuestion){const teOptionIndex=teQuestion.search(/\n\s*\([ABCD]-Telugu\)\s*/i);if(teOptionIndex>=0)teQuestion=teQuestion.slice(0,teOptionIndex).trim();}if(teQuestion)block=block.replace(/(?:^|\n)\s*Telugu Question\s*:\s*[\s\S]*$/i,'').trim();const question=enQuestion||block.replace(/(?:^|\n)\s*Telugu Question\s*:[\s\S]*$/i,'').trim();const errors=[];if(!question)errors.push('missing question');for(const k of ['A','B','C','D'])if(!enOptions[k])errors.push('missing '+k);if(!correctAnswer)errors.push('missing answer');out.push({num,question,options:enOptions,questionTe:teQuestion,optionsTe:teOptions,correctAnswer,explanation,explanationTe:teExplanation,tags:questionTags,errors,hasTelugu:!!(teQuestion||Object.values(teOptions).some(Boolean)||teExplanation)});}return out;}
function sequenceIssues(items){const nums=items.map(q=>q.num),duplicates=[...new Set(nums.filter((n,i)=>nums.indexOf(n)!==i))],missing=[];for(let n=1;n<=100;n++)if(!nums.includes(n))missing.push(n);return{duplicates,missing,outOfRange:nums.filter(n=>n<1||n>100)};}
function renderPreview(){const seq=sequenceIssues(parsed),valid=parsed.filter(q=>!q.errors.length).length,ok=parsed.length===100&&!seq.duplicates.length&&!seq.missing.length&&!seq.outOfRange.length;$('summary').innerHTML=`<span class="pill">Detected: ${parsed.length}</span><span class="pill">Valid: ${valid}</span><span class="pill">Telugu: ${parsed.filter(q=>q.hasTelugu).length}</span><span class="pill">Errors: ${parsed.length-valid}</span><span class="pill">Sequence: ${ok?'1–100 ✓':'Needs review'}</span>`;$('rows').innerHTML=parsed.length?parsed.map(q=>`<div class="row"><div>Q${q.num}</div><div><b>${esc(q.question)}</b>${q.hasTelugu?`<div class="small-options" style="color:#7dd3fc"><b>తెలుగు available</b></div>`:''}<div class="small-options">${['A','B','C','D'].map(k=>`<div><b>(${k})</b> ${esc(q.options[k])}</div>`).join('')}${q.tags.length?`<div class="small-options"><b>Tags:</b> ${esc(q.tags.join(', '))}</div>`:''}</div></div><div>${esc(q.correctAnswer||'—')}</div><div class="${q.errors.length?'bad':'ok'}">${q.errors.length?esc(q.errors.join(', ')):'Ready'}</div></div>`).join(''):'<div class="row"><div>—</div><div>No questions detected.</div><div>—</div><div class="bad">Invalid</div></div>';$('previewCard').style.display='block';const w=[];if(seq.duplicates.length)w.push(`duplicate numbers: ${seq.duplicates.join(', ')}`);if(seq.missing.length)w.push(`missing numbers: ${seq.missing.slice(0,20).join(', ')}${seq.missing.length>20?'…':''}`);if(seq.outOfRange.length)w.push(`out-of-range numbers: ${seq.outOfRange.join(', ')}`);$('sequenceWarning').textContent=w.length?w.join(' | '):'✓ Questions are in the correct Q1–Q100 sequence.';}
$('preview').onclick=()=>{parsed=parseQuestions($('source').value);renderPreview();const invalid=parsed.filter(q=>q.errors.length).length,seq=sequenceIssues(parsed),ok=parsed.length===100&&!seq.duplicates.length&&!seq.missing.length&&!seq.outOfRange.length;setStatus(!parsed.length?'No questions found.':ok&&!invalid?'✓ Found all 100 questions. They are ready to import.':`Found ${parsed.length} questions. ${invalid} need correction${ok?'.':'; check the Q-number sequence.'}`,invalid||!ok);};
$('clear').onclick=()=>{$('source').value='';parsed=[];$('previewCard').style.display='none';setStatus('');};
$('importBtn').onclick=async()=>{if(!authed)return;const valid=parsed.filter(q=>!q.errors.length),seq=sequenceIssues(parsed),ok=parsed.length===100&&!seq.duplicates.length&&!seq.missing.length&&!seq.outOfRange.length;if(valid.length!==parsed.length||!ok){setStatus('Fix validation/sequence errors before importing.',true);return;}const exam=$('exam').value.trim(),subject=$('subject').value.trim(),previousExam=$('previousExam').value.trim(),globalTags=$('tags').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),marks=Number($('marks').value)||0,negativeMarks=Number($('negative').value)||0;if(!exam||!subject){setStatus('Exam and Subject are required.',true);return;}if(!confirm(`Import all ${valid.length} questions into ${exam} → ${subject}?`))return;const btn=$('importBtn');btn.disabled=true;btn.textContent='Importing…';try{for(let i=0;i<valid.length;i+=400){const batch=writeBatch(db);if(i===0)batch.set(doc(db,'exams',examDocId(exam)),{name:exam,title:exam,subject,updatedAt:serverTimestamp(),createdBy:auth.currentUser?.email||''},{merge:true});for(const q of valid.slice(i,i+400)){const ref=doc(collection(db,'questions'));const tags=q.tags.length?q.tags:globalTags;batch.set(ref,{exam,subject,previousExam,tags,marks,negativeMarks,questionNumber:q.num,question:q.question,questionTe:q.questionTe||'',options:q.options,optionsTe:q.optionsTe,correctAnswer:q.correctAnswer,answerType:['A','B','C','D'].includes(q.correctAnswer)?'single':q.correctAnswer==='ALL'?'all':q.correctAnswer==='MULTIPLE'?'multiple':'deleted_or_all_awarded',explanation:q.explanation,explanationTe:q.explanationTe||'',hasTelugu:q.hasTelugu===true,availableLanguages:q.hasTelugu?['en','te']:['en'],answerSource:'bulk-import',createdAt:serverTimestamp()});}await batch.commit();}await setDoc(doc(db,'subjects',subjectDocId(subject)),{name:subject,updatedAt:serverTimestamp(),createdBy:auth.currentUser?.email||''},{merge:true});setStatus(`✓ Successfully imported all ${valid.length} questions into ${exam} → ${subject}.`);btn.textContent='Imported';}catch(e){console.error(e);setStatus('Import failed. Check Firestore permissions and try again.',true);btn.disabled=false;btn.textContent='Import Questions';}};

initAdmin();
